apiVersion: v1
kind: Pod
metadata:
  name: monitor
  generateName: copy-
spec:
  containers:
  - name: monitor
    image:  cr-cn-beijing.volces.com/hpcaitech/adaptdl-submit:1.12.1-cuda11.3-cudnn8-runtime-cifar10-imagenet1k
    command: ["sleep", "1000000000"]
    volumeMounts:
    - name: pollux
      mountPath: /pollux
      subPath: pollux
  volumes:
  - name: pollux
    persistentVolumeClaim:
      claimName: pollux
