apiVersion: v1
kind: Pod
metadata:
  name: monitor
  generateName: copy-
spec:
  containers:
  - name: monitor
    image: ubuntu:18.04
    command: ["sleep", "1000000000"]
    volumeMounts:
    - name: pollux
      mountPath: /pollux
      subPath: pollux
  volumes:
  - name: pollux
    persistentVolumeClaim:
      claimName: pollux
