apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pollux
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
