apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: cifar10-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - python3
        - /root/cifar10/main.py
        - --model=ResNet18
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 20
            memory: "100G"
          requests:
            nvidia.com/gpu: 1
            cpu: 20
            memory: "100G"
        volumeMounts:
        - name: data
          mountPath: /mnt
          readOnly: true
        - name: storage
          mountPath: /benchmark
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /mnt
          type: Directory
      - name: storage
        persistentVolumeClaim:
          claimName: adaptdl-data
      imagePullSecrets:
      - name: regcred
