apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: imagenet-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - python3
        - /root/imagenet/main.py
        - --arch=resnet50
        - --batch-size=128
        - --lr=0.01
        - --epochs=70
        - --autoscale-bsz
        - /benchmark/imagenet-1k
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 20
            memory: "100G"
          requests:
            nvidia.com/gpu: 1
            cpu: 20
            memory: "100G"
        volumeMounts:
        - name: data
          mountPath: /benchmark
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: adaptdl-data
      imagePullSecrets:
      - name: regcred
