apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: imagenet-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - python3
        - /root/imagenet/main.py
        - --arch=resnet50
        - --batch-size=128
        - --lr=0.01
        - --epochs=150
        - --autoscale-bsz
        - /workspace/test/imagenet-1k
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 10
            memory: "40G"
          requests:
            nvidia.com/gpu: 1
            cpu: 10
            memory: "40G"
        volumeMounts:
        - name: data
          mountPath: /workspace/test
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: adaptdl-data
      imagePullSecrets:
      - name: regcred
