apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: yolov3-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - python3
        - /root/yolov3/train.py
        - --weight_path=/benchmark/VOC/darknet53_448.weights
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 20
            memory: "100G"
          requests:
            nvidia.com/gpu: 1
            cpu: 20
            memory: "100G"
        volumeMounts:
        - name: data
          mountPath: /benchmark
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: adaptdl-data
      imagePullSecrets:
      - name: regcred
