apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: yolov3-
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workloads-to-do
                operator: In
                values:
                - do-submit
                - do-job
      containers:
      - name: main
        command:
        - python3
        - /root/yolov3/train.py
        - --weight_path=/workspace/test/VOC/darknet53_448.weights
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 10
            memory: "40G"
          requests:
            nvidia.com/gpu: 1
            cpu: 10
            memory: "40G"
        volumeMounts:
        - name: data
          mountPath: /workspace/test
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: adaptdl-data
      imagePullSecrets:
      - name: regcred
